apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-redis-credentials
  namespace: game-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: game-redis-credentials
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: cloudops-dev-redis-secret
        property: host