apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-db-secret
  namespace: game
spec:
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: game-db-credentials
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: cloudops/game-db
        property: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}/{{ .dbname }}"