apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-redis-secret
  namespace: game
spec:
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: game-redis-credentials
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: cloudops-dev-redis
        property: "redis://{{ .host }}:{{ .port }}/0"