# Default values for auth-service
replicaCount: 1

image:
  repository: auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  host: auth.example.com
  path: /
  pathType: Prefix

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

env: []
  # - name: DB_SECRET_NAME
  #   value: "cloudops/game-db"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
affinity: {}