apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "game-service.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /ready/
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 40 }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
        readinessProbe:
          httpGet:
            path: /ready/
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}