{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "game-service.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
      {{- toYaml .Values.networkPolicy.ingressFrom | nindent 6 }}
    ports:
    - port: {{ .Values.service.targetPort }}
  egress:
  - to:
      {{- toYaml .Values.networkPolicy.egressTo | nindent 6 }}
    ports:
      {{- toYaml .Values.networkPolicy.egressToPorts | default .Values.networkPolicy.egressTo | nindent 6 }}
{{- end }}