name: "Kubernetes Deploy"

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      ENV: dev
      CLUSTER_NAME: cloudops-dev-eks-cluster
      REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          submodules: recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }}

      - name: Apply Kustomize overlays
        run: |
          kubectl apply -k kubernetes/overlays/${{ env.ENV }}


      - name: Install External Secrets Operator
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update
          helm upgrade --install external-secrets external-secrets/external-secrets \
            --namespace external-secrets \
            --create-namespace \
            --wait \
            --timeout 3m

      - name: Deploy helm charts
        run: | 
          helm upgrade --install game-service ./helm/game-service \
            --namespace game-dev \
            --create-namespace \
            --values configs/dev/values-game-service.yaml \
            --set image.repository=234506497205.dkr.ecr.us-east-1.amazonaws.com/cloudops-dev-game-service \
            --set image.tag=${{ github.sha }} \
            --atomic \
            --wait \
            --timeout 5m \
            --cleanup-on-fail 

      - name: Deploy monitoring stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            -f kubernetes/monitoring/prometheus-values.yaml \
            --wait
          helm upgrade --install loki grafana/loki-stack \
            --namespace logging --create-namespace \
            -f kubernetes/monitoring/loki-values.yaml \
            --wait
          kubectl apply -f kubernetes/monitoring/grafana-dashboard-game.yaml || true
          kubectl apply -f kubernetes/monitoring/prometheus-alerts.yaml || true

      - name: Health check
        run: |
          kubectl wait --for=condition=ready pod -l app=game-service -n game-dev --timeout=120s