name: "Terraform Apply"

on:
  workflow_run:
    workflows: ["Terraform Plan & Test"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    env:
      TF_WORKING_DIR: 'terraform/environments/dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has permissions to access artifacts
          run-id: ${{ github.event.workflow_run.id }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}