name: "Terraform Apply"

on:
  workflow_run:
    workflows: ["Terraform Plan & Test"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    env:
      TF_WORKING_DIR: 'terraform/environments/dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has permissions to access artifacts
          run-id: ${{ github.event.workflow_run.id }}

      - name: Handle existing secrets
        run: |
          for secret in cloudops-dev-postgres-secret cloudops-dev-redis-secret; do
     
            STATUS=$(aws secretsmanager describe-secret \
              --secret-id $secret \
              --region us-east-1 \
              --query 'DeletedDate' \
              --output text 2>/dev/null || echo "NOT_FOUND")
      
           if [ "$STATUS" != "None" ] && [ "$STATUS" != "NOT_FOUND" ]; then
             echo "Secret $secret is in pending deletion — restoring"
             aws secretsmanager restore-secret \
               --secret-id $secret \
               --region us-east-1 || true
           fi
          done

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

        #